#include "internal/PlayerPackageBuilderInternal.h"

#include <system_error>

namespace PlayerPackageBuilderInternal {
namespace {
bool IsRegularFile(const std::filesystem::path& path) {
    std::error_code error;
    return std::filesystem::is_regular_file(path, error) && !error;
}

bool IsDirectory(const std::filesystem::path& path) {
    std::error_code error;
    return std::filesystem::is_directory(path, error) && !error;
}

bool IsDirectChild(const std::filesystem::path& parent,
                   const std::filesystem::path& child) {
    std::error_code error;
    const std::filesystem::path relative = std::filesystem::relative(child, parent, error);
    return !error && !relative.empty() && !relative.is_absolute() &&
           *relative.begin() != L"..";
}

bool IsGeneratedPackage(const std::filesystem::path& destination,
                        const std::filesystem::path& manifest) {
    if (!IsDirectory(destination)) {
        return false;
    }
    return IsRegularFile(destination / kPackageMarker) ||
           (IsRegularFile(destination / L"Game.exe") &&
            IsDirectory(destination / L"resources") &&
            IsRegularFile(destination / L"project" / manifest.filename()));
}

bool IsPackageRequestValid(const PlayerPackageRequest& request) {
    return IsRegularFile(request.executable) && IsRegularFile(request.manifest) &&
           (request.configuration == "Debug" || request.configuration == "Release") &&
           !request.destination.empty();
}

bool ResolveSafeDestination(const PlayerPackageRequest& request,
                            std::filesystem::path& destination) {
    std::error_code error;
    destination = std::filesystem::absolute(request.destination, error).lexically_normal();
    return !error && destination != destination.root_path() &&
           destination != request.projectRoot.lexically_normal() &&
           IsDirectChild(destination.parent_path(), destination);
}
}  // namespace

bool PreparePackagePlan(const PlayerPackageRequest& request, PackagePlan& plan,
                        std::string& error) {
    if (!IsPackageRequestValid(request)) {
        error = "Player package request is invalid.";
        return false;
    }
    if (!ResolveSafeDestination(request, plan.destination)) {
        error = "Player package destination is unsafe.";
        return false;
    }
    std::error_code filesystemError;
    plan.replacingPackage = std::filesystem::exists(plan.destination, filesystemError);
    if (filesystemError) {
        error = "Could not inspect the Player package destination.";
        return false;
    }
    if (plan.replacingPackage &&
        !IsGeneratedPackage(plan.destination, request.manifest)) {
        error = "Player package destination exists and was not generated by LikeEngine.";
        return false;
    }
    plan.staging = plan.destination.wstring() + L".building";
    if (std::filesystem::exists(plan.staging, filesystemError) || filesystemError) {
        error = "Player package staging directory already exists.";
        return false;
    }
    return true;
}
}  // namespace PlayerPackageBuilderInternal
