#include "PlayerPackageBuilder.h"

#include <algorithm>
#include <cwctype>
#include <fstream>
#include <system_error>

namespace {
constexpr wchar_t kPackageMarker[] = L".likeplayerpackage";

bool CopyDirectory(const std::filesystem::path& source,
                   const std::filesystem::path& destination,
                   std::error_code& error) {
    if (!std::filesystem::is_directory(source, error) || error) {
        return false;
    }
    std::filesystem::copy(
        source, destination,
        std::filesystem::copy_options::recursive |
            std::filesystem::copy_options::overwrite_existing,
        error);
    return !error;
}

bool IsCppSourceFile(const std::filesystem::path& path) {
    std::wstring extension = path.extension().wstring();
    std::ranges::transform(extension, extension.begin(), ::towlower);
    return extension == L".cpp" || extension == L".h" ||
           extension == L".hpp";
}

bool CopyProjectAssets(const std::filesystem::path& source,
                       const std::filesystem::path& destination,
                       std::error_code& error) {
    if (!std::filesystem::is_directory(source, error) || error) {
        return false;
    }
    std::filesystem::create_directories(destination, error);
    if (error) {
        return false;
    }
    for (std::filesystem::recursive_directory_iterator iterator(source, error),
         end;
         iterator != end && !error; iterator.increment(error)) {
        const std::filesystem::directory_entry& entry = *iterator;
        const std::filesystem::path relative =
            std::filesystem::relative(entry.path(), source, error);
        if (error) {
            return false;
        }
        const std::filesystem::path target = destination / relative;
        if (entry.is_directory(error)) {
            std::filesystem::create_directories(target, error);
        } else if (entry.is_regular_file(error) &&
                   !IsCppSourceFile(entry.path())) {
            std::filesystem::create_directories(target.parent_path(), error);
            if (!error) {
                std::filesystem::copy_file(
                    entry.path(), target,
                    std::filesystem::copy_options::overwrite_existing, error);
            }
        }
        if (error) {
            return false;
        }
    }
    return !error;
}

bool IsDirectChild(const std::filesystem::path& parent,
                   const std::filesystem::path& child) {
    std::error_code error;
    const std::filesystem::path relative =
        std::filesystem::relative(child, parent, error);
    return !error && !relative.empty() && !relative.is_absolute() &&
           *relative.begin() != L"..";
}

bool IsGeneratedPackage(const std::filesystem::path& destination,
                        const std::filesystem::path& manifest) {
    std::error_code error;
    if (!std::filesystem::is_directory(destination, error) || error) {
        return false;
    }
    if (std::filesystem::is_regular_file(destination / kPackageMarker, error) &&
        !error) {
        return true;
    }
    error.clear();
    return std::filesystem::is_regular_file(destination / L"Game.exe", error) &&
           !error &&
           std::filesystem::is_directory(destination / L"resources", error) &&
           !error &&
           std::filesystem::is_regular_file(
               destination / L"project" / manifest.filename(), error) &&
           !error;
}
} // namespace

bool PlayerPackageBuilder::Build(const PlayerPackageRequest& request,
                                 std::string& error) {
    error.clear();
    std::error_code filesystemError;
    if (!std::filesystem::is_regular_file(request.executable, filesystemError) ||
        filesystemError ||
        !std::filesystem::is_regular_file(request.manifest, filesystemError) ||
        filesystemError ||
        (request.configuration != "Debug" &&
         request.configuration != "Release") ||
        request.destination.empty()) {
        error = "Player package request is invalid.";
        return false;
    }
    const std::filesystem::path destination =
        std::filesystem::absolute(request.destination, filesystemError)
            .lexically_normal();
    if (filesystemError || destination == destination.root_path() ||
        destination == request.projectRoot.lexically_normal() ||
        !IsDirectChild(destination.parent_path(), destination)) {
        error = "Player package destination is unsafe.";
        return false;
    }
    const bool replacingPackage =
        std::filesystem::exists(destination, filesystemError);
    if (filesystemError) {
        error = "Could not inspect the Player package destination.";
        return false;
    }
    if (replacingPackage &&
        !IsGeneratedPackage(destination, request.manifest)) {
        error =
            "Player package destination exists and was not generated by LikeEngine.";
        return false;
    }
    const std::filesystem::path staging =
        destination.wstring() + L".building";
    if (std::filesystem::exists(staging, filesystemError) || filesystemError) {
        error = "Player package staging directory already exists.";
        return false;
    }

    const auto fail = [&](const char* message) {
        std::error_code cleanupError;
        std::filesystem::remove_all(staging, cleanupError);
        error = message;
        return false;
    };
    std::filesystem::create_directories(staging / L"project", filesystemError);
    if (filesystemError) {
        return fail("Could not create the Player package directory.");
    }
    std::filesystem::copy_file(request.executable, staging / L"Game.exe",
                               std::filesystem::copy_options::overwrite_existing,
                               filesystemError);
    if (filesystemError) {
        return fail("Could not copy the Player executable.");
    }
    const std::filesystem::path executableDirectory =
        request.executable.parent_path();
    for (const auto& entry :
         std::filesystem::directory_iterator(executableDirectory,
                                             filesystemError)) {
        if (filesystemError) {
            return fail("Could not enumerate Player runtime files.");
        }
        if (entry.is_regular_file(filesystemError) &&
            entry.path().extension() == L".dll") {
            std::filesystem::copy_file(
                entry.path(), staging / entry.path().filename(),
                std::filesystem::copy_options::overwrite_existing,
                filesystemError);
            if (filesystemError) {
                return fail("Could not copy a Player runtime DLL.");
            }
        }
    }
    if (!CopyDirectory(executableDirectory / L"resources",
                       staging / L"resources", filesystemError)) {
        return fail("Could not copy Player resources.");
    }

    const std::filesystem::path packagedProject = staging / L"project";
    std::filesystem::copy_file(
        request.manifest, packagedProject / request.manifest.filename(),
        std::filesystem::copy_options::overwrite_existing, filesystemError);
    if (filesystemError ||
        !CopyProjectAssets(request.assetRoot, packagedProject / L"assets",
                           filesystemError) ||
        !CopyDirectory(request.sceneRoot, packagedProject / L"scenes",
                       filesystemError)) {
        return fail("Could not copy the project content.");
    }
    const std::filesystem::path settings = request.projectRoot / L"settings";
    if (std::filesystem::is_directory(settings, filesystemError) &&
        !CopyDirectory(settings, packagedProject / L"settings",
                       filesystemError)) {
        return fail("Could not copy Project Settings.");
    }
    filesystemError.clear();
    const std::filesystem::path scriptAssembly =
        request.projectRoot / L"library" / L"ScriptAssemblies" / L"x64" /
        std::filesystem::path(request.configuration) / L"ProjectScripts.dll";
    if (!std::filesystem::is_regular_file(scriptAssembly, filesystemError) ||
        filesystemError) {
        return fail("Project Script DLL is missing.");
    }
    const std::filesystem::path packagedAssembly =
        packagedProject / L"library" / L"ScriptAssemblies" / L"x64" /
        std::filesystem::path(request.configuration);
    std::filesystem::create_directories(packagedAssembly, filesystemError);
    std::filesystem::copy_file(
        scriptAssembly, packagedAssembly / L"ProjectScripts.dll",
        std::filesystem::copy_options::overwrite_existing, filesystemError);
    if (filesystemError) {
        return fail("Could not copy the Project Script DLL.");
    }
    {
        std::ofstream marker(staging / kPackageMarker, std::ios::trunc);
        marker << "LikeEngine Player Package\n";
        marker.close();
        if (!marker) {
            return fail("Could not mark the Player package.");
        }
    }

    if (!replacingPackage) {
        std::filesystem::rename(staging, destination, filesystemError);
        if (filesystemError) {
            return fail("Could not finish the Player package.");
        }
        return true;
    }

    const std::filesystem::path previous =
        destination.wstring() + L".previous";
    if (std::filesystem::exists(previous, filesystemError) || filesystemError) {
        return fail("A previous Player package backup still exists.");
    }
    std::filesystem::rename(destination, previous, filesystemError);
    if (filesystemError) {
        return fail("Could not replace the existing Player package.");
    }
    std::filesystem::rename(staging, destination, filesystemError);
    if (filesystemError) {
        std::error_code restoreError;
        std::filesystem::rename(previous, destination, restoreError);
        if (restoreError) {
            error =
                "Could not publish the Player package or restore the previous package.";
            return false;
        }
        return fail("Could not publish the updated Player package.");
    }
    std::error_code cleanupError;
    std::filesystem::remove_all(previous, cleanupError);
    if (cleanupError) {
        error = "Player package was updated, but its previous backup could not be removed.";
    }
    return true;
}
